source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BRYXStackView_Example', :exclusive => true do
  pod "BRYXStackView", :path => "../"
end

target 'BRYXStackView_Tests', :exclusive => true do
  pod "BRYXStackView", :path => "../"

  
end
